### ISSUE TITLE
Unable to create folders

### ISSUE THREAD

**Issue by UncleVladd** [jon6fingrs/dovecot#2]
can't seem to create folders from either mbsync, imapsync or even in the client.
Are there any settings that need to be enabled?

**Comment by jon6fingrs** [comment]
What do you mean you can’t create folders?On Nov 12, 2024, at 4:32 PM, Uncle Vladd ***@***.***> wrote:﻿
can't seem to create folders from either mbsync, imapsync or even in the client.
Are there any settings that need to be enabled?
